### ISSUE TITLE
Implementation Details of DistFixSeq

### ISSUE THREAD

**Issue by dragonlee258079** [SirisAvishek/Attention_Shift_Ranks#3]
Thanks for your hard work.

I have some confusion about the label  of "rank order" in your dataset.  According to the method provided by formula 8 in the supplementary file to generate rank score, it should exist a situation where the rank scores of two objects are very close,(e.g. 0.93 and 0.90), so there will be two objects whose rank scores will be equal when keep one decimal place. But I haven't seen this in the dataset.  Why is the rank score in the dataset so discretized? Why are there negative numbers? Can you explain this or provide the corresponding code?

**Comment by SirisAvishek** [comment]
@dragonlee258079 

Here are the steps performed to generate rank score in terms of code:

1. For an image, go through each observer data:
give descending score to objects that have been fixated 


2. After going through all observer data:
calculate the average score for each object


3. Finally, for each object with an average score, give final saliency rank value
descending score given to objects based on their average score
saliency rank value starts from 1, and -0.1 for each consecutive object rank


Notes:
- objects with 0 value are those that were not fixated by any of the observers
- we get negative saliency values when we start to have more than 11 objects fixated (due to step 3.)


As we have mentioned in the paper we are looking for unique saliency rank order. Therefore, the object with value 0.93, will be ranked higher than object with 0.90 (in your example).

**Comment by dragonlee258079** [comment]
Thanks a lot

**Comment by ritvikagrawal1** [comment]
Dear @SirisAvishek,
I was trying to generate GT saliency rank map on a custom dataset and your paper claims to obtain it via DistFixSeq.
Can you please share the code for generating the same?
