### ISSUE TITLE
Rank Values

### ISSUE THREAD

**Issue by dylanseychell** [SirisAvishek/Attention_Shift_Ranks#5]
Hi,

Interesting work!  I have a few queries as listed below:

1) In the ASSR folder you have a JSON file in the rank_order folder with ranking values. The values vary from negative to positive with some values more negative than -1. What is the exact purpose of this file? As the algorithm should generate five rank values but in some instances, you have more than 30 values in these JSON files.

2) Why is the value generated from -1,1 for the rank (although you have some values which are over, see point 1). Why not normalise from 0,1?

3) The file obj_seg_data_val.json are the values in this file the segments for the GT? or the values generated by the mask rcnn?

Thanks!

Dylan

**Comment by SirisAvishek** [comment]
Hi Dylan,

1. The JSON files in the "rank_order" folder contain the GT saliency ranks for each image in the dataset
2. The values range from -1 to 1 due to our saliency rank generation method. We just simply use values 1-0.6 as the Top-5 ranks, all other values are considered no rank (no saliency).
3. The files obj_seg_data_{train/val/test}.json contain GT instance data for each split. They are derived from the official COCO-instance data and processed for our dataset.

Thanks,
Avishek

**Comment by dylanseychell** [comment]
Thanks for your clarification!

Dylan
